### ISSUE TITLE
(BUG) invincible metal crates

### ISSUE THREAD

**Issue by TheComicRelief** [XuuXiaolan/CodeRebirth#12]
Metal crates can't be opened, hitting it doesn't work even with shovels. 
My modpack code if you want to check it yourself: 
01929f75-cc74-ba81-27fd-0bc5b94c49fd

**Comment by XuuXiaolan** [comment]
they'll be changed in the next next version of CodeRebirth, apologies for the last response, will keep this up until they're changed, but they'll be entirely different mechanically with a new model too

**Comment by TheComicRelief** [comment]
This error pops up in the latest version

[09:51:53.1793526] [Error  : Unity Log] TypeLoadException: Could not load type of field 'CodeRebirth.src.ModCompats.OpenBodyCamCompatibilityChecker+<>O:<0>__OverrideAttachmentPoint' (0) due to: Could not resolve type with token 010000eb from typeref (expected class 'TargetChangedToTransform' in assembly '') assembly: type:TargetChangedToTransform member:(null)
Stack trace:
CodeRebirth.src.ModCompats.OpenBodyCamCompatibilityChecker.Init () (at ./src/ModCompats/OpenBodyCamCompat.cs:23)
CodeRebirth.src.Plugin.Awake () (at ./src/Plugin.cs:54)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:DMD<BepInEx.Bootstrap.Chainloader::Start>()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable() 

And i can't find any crates despite setting them to 100. Also can't find any hazards but this is untested.
My modpack code: 0192f175-3e8c-fc14-e0d9-74c513cb08d6

**Comment by XuuXiaolan** [comment]
apologies, it has been fixed, the mod was just basically not loading, also metal crates were changed, so ill be closing this issue
