### ISSUE TITLE
[BUG]: Ship in motion

### ISSUE THREAD

**Issue by dvuiodvojd** [XuuXiaolan/CodeRebirth#13]
### Installation Method

r2modman / r2mm

### What happened?

the new version of the mod make my ship stuck on the moon, i can't pull it back, it just says "Ship in motion"
i have this problem on "0.7.5 and 0.7.4", the versions before it was working fine

### What did you do?

1. Start the game
2. Landed on Assurance
3. Ship stuck

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

Swaggies-ClearanceIndicator-1.0.0
Wexop-TheThing-1.0.3
NotezyTeam-LethalMin-0.1.12
ProjectSCP-SCP999-2.1.0
Rune580-LethalCompany_InputUtils-0.7.7
Fandovec03-SpiderPositionFix-1.0.4
Fandovec03-ExperimentalEnemyInteractions-0.1.23
4902-Cruiser_Additions-1.4.0
Swaggies-ClearanceIndicator-1.0.0
ItemQuickSwitchMod
ButteryStancakes-RestoreMapper-1.0.0
Coppertiel-MaskedEnemyOverhaulFork-3.3.0
Lordfirespeed-OdinSerializer-2022.11.9
NotAtomicBomb-TerminalApi-1.5.5
Sigurd-CSync-5.0.1
StaticNetcodeLib
VirusTLNR-LethalIntelligenceExperimental-0.2.5
WhiteSpike-Interactive_Terminal_API-1.1.3
xilophor-LethalNetworkAPI-3.2.1
ReavsStuff-ShibaBatInu-0.0.5
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.6.5
bctix-FPSCounter-1.4.0
347956-JPOGStegosaurus-1.0.1
347956-JPOGTrex-1.1.2
AinaVT-LethalConfig-1.4.2
AllToasters-SpectateEnemies-2.6.0
enmaai0737-RollerEnemy-1.0.5
XuXiaolan-TheGiantSpecimens-2.2.1
YaBoiDucki-men_stalker-2.4.0
zealsprince-Locker-1.2.6
JacobG5-ReverbTriggerFix-0.3.0
jaspercreations-Scopophobia-1.1.5
MegaPiggy-EnumUtils-1.0.5
Lembont-Mantle-1.0.2
MoonsweptTeam-Moonswept-0.5.8
ReavsStuff-HitchBloodsworth-0.0.3
SolidStone-ShockwaveDroneEnemy-0.6.3
SolidStone-SolidLib-1.2.2
super_fucking_cool_and_badass_team-Biodiversity-0.1.3
SurfacedTeam-Surfaced-1.4.1
Wexop-CountryRoadCreature-1.0.6
Jordo-NeedyCats-1.2.2
XuXiaolan-PjonkGoose-1.4.1
MrHydralisk-EnhancedRadarBooster-1.7.1
mrov-MrovLib-0.2.4
mrov-TerminalFormatter-0.2.23
qh3-EasyVehicle-1.0.0
SylviBlossom-SmartItemSaving-1.2.4
Zehs-SellMyScrap-1.6.2
Asonyx-LethalSleep-0.1.0
BaronDrakula-MoreCounterplay-1.4.0
Swaggies-BetterPaycheck-0.9.0
mrov-WeatherRegistry-0.1.25
Terraformer9x-RebalancedMineshaft-0.3.0
TestAccount666-GoodItemScan-1.10.0
WhiteSpike-Weather_Probe-1.0.0
EliteMasterEric-CleanerLogs-1.0.0
Bobbie-FixRPCLag-1.0.1
ButteryStancakes-ButteryFixes-1.9.0
EugeneWWolf-VanillaMoonsLagFix-1.0.3
tinyhoot-ShipLoot-1.1.0
WhiteSpike-Extend_Deadline-1.0.2
Alainx277-Lethal_Crumbs-1.1.0
DaXcess-NoJumpDelay-1.0.0
MMHOOK
IAmBatby-LethalLevelLoader-1.3.10
MaxWasUnavailable-LethalModDataLib-1.2.2
Evaisa-LethalLib-0.16.1
HDLethalCompany
fumiko-CullFactory-1.3.12
LethalPerformance
linkoid-DissonanceLagFix-1.0.0
Zaggy1024-PathfindingLagFix-1.4.0
ShaosilGaming-GeneralImprovements-1.4.3
DiggC-CruiserImproved-1.4.1
Entity378-SellBodiesFixed-1.10.1
FlipMods-BetterStamina-1.5.4
FlipMods-FasterItemDropship-1.3.1
FlipMods-LetMeLookDown-1.0.2
FlipMods-ReservedItemSlotCore-2.0.37
FlipMods-ReservedFlashlightSlot-2.0.8
FlipMods-ReservedWeaponSlot-1.1.5
Fredolx-MeteoMultiplier-1.1.3
Kamppix-QuotaScalingMoons-0.2.2
MoonJuice-BuyRateSettings-1.3.2
Rocksnotch-ShovelFix-1.1.0
SimonTendo-LCGoldScrapMod-1.7.2

### Relevant log output

```PowerShell
its saying the log is too big D:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dvuiodvojd** [comment]
the version is v64, idk its is appearing v49

**Comment by XuuXiaolan** [comment]
Can you send the log in the discord thread for this mod maybe?

**Comment by dvuiodvojd** [comment]
> Can you send the log in the discord thread for this mod maybe?

where i do it? i'm on the unofficial lethal company discord server but i can't find it

**Comment by XuuXiaolan** [comment]
https://discord.com/channels/1168655651455639582/1241786100201160784

It's the official lcmod discord

**Comment by dvuiodvojd** [comment]
okay i will message

**Comment by XuuXiaolan** [comment]
was resolved
