### ISSUE TITLE
[BUG]: Cannot get Delilah/Shockwave Girl not to attack Hoarding Bugs in the config

### ISSUE THREAD

**Issue by ConnaKazie** [XuuXiaolan/CodeRebirth#17]
### Installation Method

Thunderstore Mod Manager

### What happened?

IGNORE I figued it out. Turns out it's "Hoarding bug" the B has to be lower case bruh :/

Title says it all, having no issues with any other enemies, even modded ones, but Hoarding Bugs aren't working. 
I have tried: 
Hoarding Bug
Hoarder
Hoarder Bug

No idea if it's a bug or I'm just unable to find the correct name, if I am simply not finding the correct name can you please tell me it lmao

### What did you do?

Delilah keep killin' yippee muthafuckas

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

I doubt this is necessary for this minor issue. However do have the Yippee mod by sunnobunno if that changes their name. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
My bad for not responding but putting "Hoarding bug" seemed to work for me in testing, I'll try again in a few minutes

**Comment by XuuXiaolan** [comment]
yep, "Hoarding bug" works for me
