### ISSUE TITLE
Suggestion: Spawn Weight

### ISSUE THREAD

**Issue by KyberCrow** [XuuXiaolan/CodeRebirth#18]
I think this mod is wonderful, but I'm just never a fan of guaranteed spawns, and would much rather configurable weighting like any other mob. The microwave, bear traps, and other additions are cool...if you don't see them every single round. It gets monotonous after a while.

**Comment by XuuXiaolan** [comment]
You might like the new spawning system using a curve, check the explanation in the readme

**Comment by KyberCrow** [comment]
Brilliant, thank you, this is an awesome change. I'm probably not going to touch the curves you've configured by default though, as it's a tad confusing to me.

I noticed that bear traps & AC fans still follow the old system however—curious what the reason for that is, or if it's just not implemented for all hazards yet.

But thanks again!

**Comment by XuuXiaolan** [comment]
As they're outside hazards I'm not able to smoothly change how they work unless I rewrite a lot of what I do currently
