### ISSUE TITLE
(NOT A BUG, just confused) how do indoor hazards spawn work?

### ISSUE THREAD

**Issue by TheComicRelief** [XuuXiaolan/CodeRebirth#19]
I don't understand how the new curve spawn weight works. Like, at all.

**Comment by XuuXiaolan** [comment]
There's an explanation in the readme I believe

**Comment by Skyblade799** [comment]
I was wondering the same, but I couldn't seem to find it in the readme? I only saw explanations on the weather types.

**Comment by XuuXiaolan** [comment]
the big bold "HAZARD CONFIG" section near the top of the readme?

**Comment by Skyblade799** [comment]
> the big bold "HAZARD CONFIG" section near the top of the readme?

I'm definitely not looking at the same readme then. I'm looking at the readme in github here that starts with:

"Code:Rebirth

Overhaul mod for Lethal Company
Contribute

[Make a fresh rip using nomnom's Unity LC Patcher tool and name it CodeRebirthUnityProject](https://github.com/nomnomab/unity-lc-project-patcher)

Copy the CodeRebirth folder in CodeRebirthUnityProject/Assets/LethalCompany/Mods/plugins/CodeRebirth <--"

It continues from there, just containing weather descriptions for weather that doesn't seem to exist in the mod, followed by some sections that were drafted with no text. Is it not the README.md in the main github code?

**Comment by Skyblade799** [comment]
In fact, just posting the whole readme.md:

"

Code:Rebirth

Overhaul mod for Lethal Company
Contribute

    [Make a fresh rip using nomnom's Unity LC Patcher tool and name it CodeRebirthUnityProject](https://github.com/nomnomab/unity-lc-project-patcher)

    Copy the CodeRebirth folder in CodeRebirthUnityProject/Assets/LethalCompany/Mods/plugins/CodeRebirth <--

    Paste it into that Unity Project's plugins folder

    Move the fresh asset-ripped project into the root files (same root as the README.md), replacing the original CodeRebirthUnityProject with this one.

    Done!

    To make the CodeRebirth.csproj.user work properly, COPY the template version and get rid of the .template at the end in the copy. simple!

Weathers
Ion Storm

    Availability: Universal
    Effects: Creates a thick fog and intermittent electrical bolts, simulating a toned-down lightning storm. Disables all electronic devices outdoors. Delays delivery times by double.

Sandstorm

    Availability: Sandy Moons (e.g., Offense)
    Effects: Significantly slows player movement and reduces visibility. Small scrap items may be blown away if not secured.

Rogue Waves

    Availability: Watery Moons
    Effects: Water levels fluctuate dramatically and unpredictably. A new item, a life preserver, can be purchased to prevent drowning.

Blackout

    Availability: Universal
    Effects: External lights fail and internal lights flicker, turning off and on every few minutes in real life.

Orbital Drops

    Availability: Worlds like Artifice, Embrion, and those with Old-Bird presence
    Effects: Randomly, every 30 minutes to 6 hours, an Old Bird drops from orbit, activated upon arrival. There is a chance an existing Old Bird is awakened instead of a new one dropping.

Orbital Bombardment

    Availability: Same as Orbital Drops
    Effects: Sirens warn of incoming orbital barrages that last up to a minute, causing significant damage to anything outdoors. Occasionally, inactive bombs can be collected as valuable scrap.

Enchantment

    Availability: Forested Moons
    Effects: Certain areas are enveloped in a glowing purple mist that pacifies creatures and grants a temporary boost to players, similar to a TZP effect.

Heatwave

    Availability: Non-snowy Moons
    Effects: Causes heat ripples, faster stamina drain, and increased movement penalty due to heat. Reduces enemy spawn rates outdoors.

Fire Tornadoes

    Availability: Desert and Hot Moons
    Effects: Creates fiery tornadoes that cause damage when in close proximity, using visuals similar to those from HD2's Old-Bird-fire-like particles.

Blood Moon

    Availability: Any moon that has an entry fee above a certain threshold
    Effects: Increases enemy spawn rate and power level both inside and outside the facility. The environment becomes dark all day with a blood-red eclipsed sun, making it more challenging than typical eclipsed conditions.

Impact on Gameplay

[How this weather affects player strategies, enemy behavior, or game environment.]
Misc
[Miscellaneous Category]
Description

[General description or list of miscellaneous items, features, or game mechanics to be added.]
Feature: [Feature Name]
Functionality

[Description of what the feature does and how it integrates into the game.]
Importance
[Why this feature is essential or beneficial to the game.]

"

**Comment by XuuXiaolan** [comment]
the readme on Thunderstore, not github

**Comment by Skyblade799** [comment]
Ahh, thank you! That's exactly what I was looking for. Might not be a bad idea to have it directly in the config descriptions somewhere.

**Comment by TheComicRelief** [comment]
Ok. Just to make sure, if I, for example, have the industrial fans spawn curve be
0,0 ; 0.3,1 ; 0.7,1 ; 1,2
Then there would be average of 1 and maximum of 2, right?

**Comment by XuuXiaolan** [comment]
i dont think it ever rounds up tbh, so you wont really get 2 unless you do like:
0,0 ; 0.3,1 ; 0.7,1 ; 1,3

**Comment by TheComicRelief** [comment]
Then you need to recheck the code. Because this is the exact same curve I used for experimentation and there were 4 of them.

**Comment by XuuXiaolan** [comment]
huh, for now i'd try to not have teh same numbers for any coordinates and see if that does anything, but i did manage to reproduce so ill let you know if anything specific is the problemn
