### ISSUE TITLE
[Balance issue] Microwave item sell value

### ISSUE THREAD

**Issue by Zeta-Arcade** [XuuXiaolan/CodeRebirth#21]
The sell value of scraps from the microwaves are extremely high, likely an oversight. Paired with it being low-risk, the previous recommendation to have microwaves spawn numerously to make them more effective hazards, and no config to control the value / spawn rate of said microwave scraps, they break the balance of moons very quickly, especially if a microwave hell occurs with the new spawn curve system.
![image](https://github.com/user-attachments/assets/048f961b-6e83-4e5d-8bcb-956174d27c9f)
![image](https://github.com/user-attachments/assets/99211148-d690-43fa-a026-dcce276e21e6)

An option to disable this feature or to be able to control the value / spawn chances of the scrap would be much appreciated. For now on my end we'll need to just temporarily disable microwaves for the pack until theres a fix.

**Comment by XuuXiaolan** [comment]
fixed next update
