### ISSUE TITLE
[Bug] Items from microwaves desync/spawn on the floor for clients

### ISSUE THREAD

**Issue by Zeta-Arcade** [XuuXiaolan/CodeRebirth#22]
I'm sure you've been reported this issue already and are working on it, but just in case, its as the title says.
It seems inconsistent, as sometimes for clients they see the scraps inside the microwave, other times its on the floor.
Gale modpack code: 01936e44-67bb-d11e-613f-5af5aa86f2f5
Attached log, though i dont recall any errors.
[LogOutput.log](https://github.com/user-attachments/files/17936752/LogOutput.log)

**Comment by XuuXiaolan** [comment]
slightly fixed next update, you'll see ig
