### ISSUE TITLE
(NOT A BUG) A cfg for the audio level of the traps would be nice

### ISSUE THREAD

**Issue by explodingp** [XuuXiaolan/CodeRebirth#23]
### Installation Method

r2modman / r2mm

### What happened?

They are a little loud and hurt my ears

### What did you do?

They are a little loud and hurt my ears

### Version

v68

### What OS are you running?

Windows 10

### List of mods used

They are a little loud and hurt my ears

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
completely forgot about this, will be coming next update, so tonight
