### ISSUE TITLE
[QOL]: Sea mine gal attack

### ISSUE THREAD

**Issue by QwertyRodrigo** [XuuXiaolan/CodeRebirth#24]
### Installation Method

r2modman / r2mm

### What happened?

Note to xu:
1. Make SM explosion attack more reliable and bigger range so she doesnt miss as much
2. Make her kill killable enemies so they can still have drops

### What did you do?

N/A

### Version

v68

### What OS are you running?

Windows 10

### List of mods used

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
did allat
