### ISSUE TITLE
[BUG]Sometimes robots cannot enter and exit the fire door correctly

### ISSUE THREAD

**Issue by AlanCratys** [XuuXiaolan/CodeRebirth#27]
![9973ebb4a92be113d7e3a97e011a7d7d](https://github.com/user-attachments/assets/7899ec46-5b7a-467b-b302-139f93a1f7cd)
[LogOutput.log](https://github.com/user-attachments/files/18052432/LogOutput.log)

**Comment by AlanCratys** [comment]
![7a28ae5097feebf34e19b26740da8ed6](https://github.com/user-attachments/assets/fae2b239-014f-4ca2-af00-6e81dace0362)
SEAM sometimes turns into stickman and temporarily loses its function

**Comment by XuuXiaolan** [comment]
what moon was that on?

**Comment by AlanCratys** [comment]
I don't remember the exact planet, but most of them belong to https://thunderstore.io/c/lethal-company/p/demonmae/moons _ of _ otherworld _ oddity/,and almost all of them have the problem that they can't get in and out from the fire door normally.

**Comment by QwertyRodrigo** [comment]
Sea mine gal dancing bug has been fixed
