### ISSUE TITLE
[BUG]: microwave issues

### ISSUE THREAD

**Issue by QwertyRodrigo** [XuuXiaolan/CodeRebirth#31]

**Comment by QwertyRodrigo** [comment]
-Fix scp 999 not being usable by clients
-Add bellcrab gal dance anim when a boom box plays
-Try to fix scp 999 anims (thats more on me)
-Sea mine gal staying in attack mode issue?
-Exploding wooden crate anim
-Make scp 999 fully heal lizzie without using a charge when lizzie walks by
-Scp999 reviving desync if body is not in the same position for client and host

**Comment by QwertyRodrigo** [comment]
-Make shockwave gal able to be activated on company moon like sea mine gal

**Comment by QwertyRodrigo** [comment]
- Scp999 anim issues (Squish anim and fail anims not playing for client)
- Sea mine gal cant kill redwood
- Redwood anim breaking (Starts to slide with no anims)
- Gals getting stuck in modded interiors failsafe, make them fly to ship after a while stuck
- crab gal and scp 999 dancing desync for clients, they keep dancing even if a boombox is off

**Comment by XuuXiaolan** [comment]
- tornado in a bottle, allows u to double jump

**Comment by QwertyRodrigo** [comment]
- glitch is badl

**Comment by xntkrnl** [comment]
> * glitch is badl

true

**Comment by XuuXiaolan** [comment]
> * glitch is bald

![image](https://github.com/user-attachments/assets/f1520c6c-1367-4406-b27d-577d987dc6bf)

**Comment by xntkrnl** [comment]
![image](https://github.com/user-attachments/assets/f6455cb4-c4b5-4c83-a99f-5e0c0aa81cbd)

**Comment by XuuXiaolan** [comment]
- Config for aircontrolunit

**Comment by XuuXiaolan** [comment]
- Make scaryshrimp throwable.
