### ISSUE TITLE
[BUG]: SEAM sometimes turns into stickman and loses its function

### ISSUE THREAD

**Issue by AlanCratys** [XuuXiaolan/CodeRebirth#32]
### Installation Method

r2modman / r2mm

### What happened?

SEAM sometimes turns into stickman and loses its function

### What did you do?

I activate SEAM after the spacecraft lands, and sometimes I become a stickman, whether indoors or in the company building.

### Version

v68

### What OS are you running?

Windows 10

### List of mods used

0193b10d-5e80-f019-37b8-508e96f2a050

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlanCratys** [comment]
[LogOutput.log](https://github.com/user-attachments/files/18081369/LogOutput.log)
![63148dbc78d7ae3024603239caea7de9](https://github.com/user-attachments/assets/19139286-2f01-45e7-96dc-9c3797b6a01d)
![c68062e475d4c7bc5fdc7eb67dd7c236_0](https://github.com/user-attachments/assets/2e42e167-8e17-4b51-858f-8114fc04a67d)

**Comment by XuuXiaolan** [comment]
don't play a boombox next to her, she loses functionality until the boombox is far enough away.
anyway fixed the model issue in here.
