### ISSUE TITLE
[Feature Request] SCP-999 Gal Revive Charges Scaling

### ISSUE THREAD

**Issue by Zeta-Arcade** [XuuXiaolan/CodeRebirth#33]
An option to have the amount of revives available to SCP-999 Gal scale depending on how many players are in the lobby at the start of the quota/day (depending on the recharge config) would be very interesting, much like how GeneralImprovements increases the starting credits by a flat value per additional player in the lobby. 
E.g. So you can set the base amount of revives to 1, and then add 1 for each additional player in the lobby, so 2 revives when playing as a Duo, 4 when 4 players are in the lobby etc.

This also makes balancing it when considering different lobby sizes quite easy, AND would help me make a hardcore permadeath pack thats not AS awful, hence why i've hesitated so far lol

**Comment by XuuXiaolan** [comment]
Done
