### ISSUE TITLE
[BUG]: A Weight bug about hoverboard, and another one

### ISSUE THREAD

**Issue by habacksill** [XuuXiaolan/CodeRebirth#34]
### Installation Method

r2modman / r2mm

### What happened?

I was testing with my mod pack, but if i take off the hoverboard with holding mode, my weight is still heavy
[제목 없는 동영상 - Clipchamp로 제작.zip](https://github.com/user-attachments/files/18135980/-.Clipchamp.zip)
also sometimes hoverboard is clipping down when i touched to hoverboard(up to down)
And if I get off while on the hoverboard, I can't hear my footsteps.

### What did you do?

1. Take off from hoverboard with held mode

1.Ride on a hoverboard
2. Get off while riding a hoverboard(If you get off while holding it in your hand, the footsteps will return)

### Version

v68

### What OS are you running?

Windows 11

### List of mods used

[새 텍스트 문서.txt](https://github.com/user-attachments/files/18135966/default.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
fixed with dev version, sorry for the late response
