### ISSUE TITLE
[BUG]: Robot Gals kill Pikmin [Lethalmin mod on Thunderstore]

### ISSUE THREAD

**Issue by Fellow9000** [XuuXiaolan/CodeRebirth#40]
### Installation Method

r2modman / r2mm

### What happened?

Tried out the shockwave drone gal and sea mine gal with the Lethalmin mod, they killed the Pikmin and wasted their charge. Pikmin are supposed to be passive, and aid in transporting scrap and attacking creatures, and they already die to everything, making larger armies already dificult to manage, especially if they all blow up when the robots mistake them for enemies.

### What did you do?

1. Downloaded Code Rebirth and Lethalmin along with several other mods
2. Started a level and landed on a moon
3. Plucked a Pikmin / found wild Pikmin inside facility
4. Giant laser blast performed by shockwave gal / Sea mine gal blew up in alternate test

### Version

v68

### What OS are you running?

Windows 10

### List of mods used

BepInEx-BepInExPack-5.4.2100
akechii-DiscountAlert-2.3.0
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-StaticNetcodeLib-1.1.1
EliteMasterEric-Coroner-2.2.0
Piggy-Piggys_Reanimation-1.0.0
Swaggies-BetterPaycheck-0.9.0
thomas-AlwaysShowClock-1.0.0
BlueAmulet-LCBetterClock-1.0.3
matsuura-HealthMetrics-1.0.2
ButteryStancakes-AccurateStaminaDisplay-2.2.0
Nilaier-NilsHUD-1.0.6
Piggy-ShowCapacity-1.0.9
DeathGOD7-LCItemValue-1.0.0
tinyhoot-ShipLoot-1.1.0
CTNOriginals-CrossHair-1.1.2
Zehs-Hitmarker-1.2.3
PostMortem-BetterLightning-1.0.3
Barnitto-LightningItemSlot-0.0.1
taffyko-NiceChat-1.2.7
Monkeytype-HideChat-1.0.0
JulianMods-OpenMonitors-1.1.1
kRYstall9-FastSwitchPlayerViewInRadar-1.3.2
ButteryStancakes-Chameleon-1.3.0
Spyci-CozyImprovements-1.2.2
Rune580-LethalCompany_InputUtils-0.7.7
Gemumoddo-LethalEmotesAPI-1.15.9
Gemumoddo-BadAssCompany-1.1.12
SlapItNow-LethalHands-22.1.5
FlipMods-TooManyEmotes-2.2.14
darmuh-OpenLib-0.2.11
x753-More_Suits-1.4.5
Verity-TooManySuits-2.0.1
404_Dom-Doms_Basic_Suit_Colors-1.4.4
ViViKo-MoreMaterials-1.3.2
ViViKo-CleanSuitColors-1.1.0
BatTeam-LethalFashion-1.0.7
Hexnet111-SuitSaver-1.2.1
TeamClark-Vault_Boy_Suit-1.0.0
TeamClark-SCP_Foundation_Suit-1.1.0
TeamClark-CombineEliteSuit-1.0.2
Regretti-ClassicDoomguy-1.0.0
BunyaPineTree-ModelReplacementAPI-2.4.12
TRIPLEX-Doomguy_model-0.1.0
Pee_John_Labs-Lethal_Master_Chief-0.1.0
Namirus-HelldiversModelsSuits-0.1.10
BunyaPineTree-LethalFortress2-0.1.1
Pee_John_Labs-Lethal_Ugandan-0.1.0
xilophor-LethalNetworkAPI-3.3.1
BMX-LobbyCompatibility-1.3.0
loaforc-VoiceRecognitionAPI-2.0.0
JS03-LC_VEGA-3.1.0
Nilaier-NavigatingStars-0.0.4
MasterAli2-TeleportDecline-1.1.0
Zaggy1024-OpenBodyCams-3.0.3
Verity-3rdPerson-1.1.0
ColtG5-CreepyBrackens-1.0.2
Drakorle-MoreItems-1.0.2
FlipMods-LetMeLookDown-1.0.2
TheFluff-FairAI-1.4.1
taffyko-BetterSprayPaint-2.0.9
PortableNavi-BetterInverseTeleporter-1.0.2
CTNOriginals-OuterDoorButtons-1.0.2
CTNOriginals-MonitorDoorButtons-1.1.1
SleeplessKyru-SnapRotateFurniture-1.0.1
guy7cc-LCNoPropsLost-1.0.0
HarmlessTaco-BetterBoomBox-1.0.0
TwinDimensionalProductions-CoilHeadStare-1.0.9
MrHydralisk-EnhancedRadarBooster-1.7.1
Nyxchrono-DoorBreach-1.1.0
TestAccount666-DoorBreach-1.1.0
necrowing-StopBeesOpeningDoors-1.1.0
bozzobrain-BetterDoorWarning-1.0.1
Toshizuno-BlackoutHazards-1.0.2
Scoops-LethalPhones-1.0.11
MrHydralisk-EnhancedLockpicker-1.1.6
NutNutty-AlwaysPickup-1.2.0
PotatoCoders-MinimumQuotaFinder-1.1.4
Evaisa-FixPluginTypesSerialization-1.1.1
NotAtomicBomb-TerminalApi-1.5.5
thej01-TerminalSeedPicker-1.0.0
Beauver-ExtraTerminalCommands-1.5.0
fivetoofive-DetailedScan-1.2.2
NavarroTech-TerminalKeyBindings-1.0.0
FlipMods-BetterStamina-1.5.4
Swaggies-HandsNotFull-1.1.0
FlipMods-ReservedItemSlotCore-2.0.39
FlipMods-ReservedFlashlightSlot-2.0.8
FlipMods-ReservedWalkieSlot-2.0.6
FlipMods-ReservedWeaponSlot-1.1.5
RedCrowbar-BuffedPresents-0.0.5
Sehelitar-Zaprillator-1.0.2
OpJosMods-ReviveCompany-1.4.0
DaJadeNinja-NiceAutopilot-1.0.1
ButteryStancakes-JetpackFixes-1.5.0
ShaosilGaming-GeneralImprovements-1.4.4
Dev1A3-LethalFixes-1.2.4
mrov-LightsOut-0.1.3
fumiko-CullFactory-1.5.0
TestAccount666-RandomSlimeColor-1.1.1
Evaisa-HookGenPatcher-0.0.5
Rocksnotch-ShovelFix-1.1.0
TREEPDEEP-JustJump-1.0.1
MaxWasUnavailable-LethalModDataLib-1.2.2
IAmBatby-LethalLevelLoader-1.3.13
Project_BlueFlame-Stable_Zap_Gun-1.1.0
mrov-ApparatusFix-0.0.1
Hardy-LCMaxSoundsFix-1.2.0
KarmaModding-NoFacingFireExit-1.0.0
Augur-RemoveCameraFilter-1.0.0
AinaVT-LethalConfig-1.4.3
Swaggies-ClearanceIndicator-1.0.0
sfDesat-ViewExtension-1.3.0
LethalCompanyModding-Doorbelle-1.0.2
monkes_mods-JumpDelayPatch-1.0.1
DarthLilo-MagnetLock-1.2.0
ThePotato-scanForItemsFix-1.0.4
ironbean-MeteorShowerChance-1.1.1
Zesa-NoClockSound-1.0.0
TKronix-DoorlessStorage-1.0.0
TestAccount666-AntiSlimeCamp-2.0.0
Hackattack242-Lethal_Weight_Fix-1.1.1
giosuel-ToiletPaperNormalizer-1.0.0
mrov-MrovLib-0.2.11
mrov-WeatherRegistry-0.3.9
LethalCompanyModding-VertexLibrary-1.1.0
mattymatty-Matty_Fixes-1.1.31
LethalCompanyModding-RuntimeIcons-0.3.0
JacobG5-LostEnemyFix-1.1.0
Zaggy1024-PathfindingLagFix-1.4.0
DiFFoZ-HarmonyXTranspilerFix-1.1.0
DiFFoZ-LethalPerformance-0.5.0
EliteMasterEric-SlimeTamingFix-1.0.2
Rosentti-JesterTimeout-1.0.1
TheFluff-EverythingCanDie-1.3.0
Piggy-DeathAnimationss-0.0.2
Evaisa-LethalLib-0.16.2
Toybox-LittleCompany-1.3.16
XuXiaolan-ChainsawBasher-1.1.0
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
Dackie-SCP106-3.0.1
Snowlance-WearableItemsAPI-0.1.9
ProjectSCP-HeavyItemSCPs-1.3.2
TheWeavers-LethalBestiary-1.2.1
ProjectSCP-SCP173-1.0.1
Lennozeros-Reaper_Leviathan_Thumper-1.0.4
Lanthvelian-SqueakyThumper-1.0.0
ProjectSCP-SCP500-1.0.1
nothingbutfemboys-RedPillEnemySpawn-0.2.3
VirusTLNR-LethalIntelligenceExperimental-0.3.3
NotezyTeam-LethalMin-0.2.19
Kittenji-NavMeshInCompany-1.0.3
AudioKnight-StarlancerAIFix-3.8.4
Lega-SawTapes-1.1.5
SolidStone-Scp_049_The_Plague_Doctor-1.0.2
jaspercreations-Scopophobia-1.1.5
ButteryStancakes-SnowyHolidayDropship-1.1.1
Zingar-SecretLabs-3.4.1
MrUnrealTeam-SchoolMoon-1.3.0
DemonMae-oneshotmoons-1.11.1
JacobG5-JLL-1.8.0
DemonMae-oneshotinteriors-2.1.1
DemonMae-Darkworld_Interior-1.4.3
GunbladeSenpai-FlashbbangEarrape-1.4.0
Sehelitar-IQuit-1.1.0
Confusified-KillBind-2.2.2
ZModding-VineBoomLightning-1.0.4
Sophisticasean-KeysLockDoors-1.1.3
Woecust-Immersive_Visor-0.5.2
Owen3H-IntroTweaks-1.5.0
mrgrm7-LethalCasino-1.1.2
Piggy-Piggys_Variety_Mod-1.3.17
Nexor-InstantBuy-0.0.5
echoman-LCFlashCommandFix-0.0.1
theMenagerie-LiminalPools-1.0.14
MegaPiggy-BuyableShotgun-1.3.0
MegaPiggy-BuyableShotgunShells-1.3.0
mattymatty-BagConfig-0.0.5
Zehs-MelaniesVoice-1.1.0
anormaltwig-LateCompany-1.0.18
Kittenji-Dont_Touch_Me-1.2.4
x753-Peepers-1.0.3
tolstj-TurretAlwaysLaser-1.0.0
Suki-LCTeleporterAnomaly-0.1.1
FlipMods-FasterItemDropship-1.3.1
mattymatty-DoNotEatItems-2.1.1
GangGang-NoInverseTeleporterCD-1.0.0
Mordrog-InverseTeleporterToPlayer-1.0.0
Dev1A3-BetterVehicleControls-1.1.3
4902-Cruiser_Additions-1.4.2
DiggC-CruiserImproved-1.4.1
33mamaster-LifetimeCruiserWarranty-1.4.0
JacobG5-MultiCruiser-1.0.0
ButteryStancakes-VentSpawnFix-1.2.2
taffyko-NameplateTweaks-1.0.7
Wexop-RandomColors-1.0.4
Cryptoc1-LC_DOOM-1.1.2
berserke-EpicNutcracker-1.0.2
PugRoll-TripleJump-1.0.0
Nexor-ControllableExplosiveEgg-0.0.7
mattymatty-LandFromOrbit-1.1.2
ViViKo-BetterShipDoors-1.0.0
loaforc-FacilityMeltdown-2.6.20
den-Meltdown_Chance-2.7.0
ButteryStancakes-MeleeFixes-1.3.1
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.6.5
mattymatty-AsyncLoggers-2.1.3
mborsh-Useful_Zap_Gun-0.2.0
ButterCookie-CookieKnife-1.1.2
Sigurd-CSync-5.0.1
consequential-Oxygen-1.6.3
TestAccount666-ShipWindows-1.11.0
sfDesat-Celestial_Tint-1.5.2
Graze-MenuMusicMute-1.0.0
AudioKnight-StarlancerEnemyEscape-2.5.7
mrov-OrbitRecharge-0.1.0
FloofMods-WirelessCharging-1.0.0
mattymatty-FurnitureLock-1.3.6
dopadream-Motion_Tracker_V3-1.0.9
Backrooms-Backrooms-0.1.3
TestAccount666-RealBackroomsPatch-1.4.0
WhiteSpike-Helmet-1.0.0
Mellowdy-HandheldMap-1.6.2
BGN-PizzaTowerEscapeMusic-2.4.0
FlipMods-ReservedUtilitySlot-1.0.6
HugotheDwarf-Ammo_Tin-1.1.0
HugotheDwarf-Ammo_Tin_Piggy_Compat-1.0.1
LCModders-Better_Cruiser_SFX-1.0.0
FlipMods-NoMusicDistortion-1.0.4
ButteryStancakes-RestoreMapper-1.0.0
Inoyu-Giant_Extension_Ladders-3.3.0
Inoyu-Fast_Climbing-1.3.0
Cobster-FireExitLadders-1.0.1
Megalophobia-Longer_Day-1.0.0
La_chips-AutoCompanyBuilding-1.2.1
Kyryh-ToreadorMarchJester-1.0.1
SillySquad-BetterTotalScrap-1.1.1
ironbean-AmmoIndicator-1.0.1
Rissoe-LcApparatusTimer-1.0.1
SimonTendo-LCPaperCompanyMod-1.0.8
MasterAli2-BetterBabies-0.1.2
mrov-TerminalFormatter-0.2.23
woah25-FairBirds-1.0.1
LegoMaster3650-FairGiants-1.1.2
bmatusiak-FreeeeStoooore-1.0.1
Kyra-NicestTeleporters-1.0.0
darmuh-suitsTerminal-1.5.12
Wexop-TheThing-1.0.5
Zigzag-PremiumScraps-2.1.0
XuXiaolan-CodeRebirth-0.9.6

### Relevant log output

```PowerShell
[Log output exeded 65536 characters]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
I can add it to the default but what you have to do is go to the configs for the shockwave gal and seamine gal and add Pikmin to the enemy blacklist

**Comment by QwertyRodrigo** [comment]
Yeah add any enemy/creature you dont want them to kill in the blacklist

**Comment by XuuXiaolan** [comment]
added to release
