### ISSUE TITLE
[BUG]: Microwaves cause random explosions on moons for clients

### ISSUE THREAD

**Issue by CobaltDunlin** [XuuXiaolan/CodeRebirth#43]
### Installation Method

r2modman / r2mm

### What happened?

Microwaves don't seem to explode inside when they have items inside of them, instead the explosions will happen on the moon outside. This doesn't seem to happen for the host, but clients have complained about random explosions that can damage them after we land.

### What did you do?

1. We land on a moon
2. Occasionally for clients, random explosions will happen outside, sometimes damaging them

### Version

v68

### What OS are you running?

Windows 10

### List of mods used

BepInEx-BepInExPack-5.4.2100
LethalCompanyModding-LCUltrawide_Community-1.1.3
x753-More_Suits-1.4.5
FlipMods-ObjectVolumeController-1.1.1
404_Dom-Doms_Basic_Suit_Colors-1.4.4
Crab_imitation-EmissiveSuits-1.0.0
DisappointedScrubs-More_Suits_Scrub_Skins-1.0.6
Dielji-StreamerSuits-1.1.8
Kmoto-Kmoto_suits3-1.1.2
happyfrosty-FrostySuits-2.0.0
happyfrosty-FrostySuits2-1.0.9
ManiaBania-1000_Quota_Stare-1.0.0
sunnobunno-YippeeMod-1.2.4
notnotnotswipez-MoreCompany-1.11.0
happyfrosty-FrostyCosmetics-1.0.7
EliteMasterEric-WackyCosmetics-2.0.0
tinyhoot-ShipLoot-1.1.0
FlipMods-BetterStamina-1.5.4
FlipMods-TooManyEmotes-2.2.14
taffyko-BetterSprayPaint-2.0.9
DaXcess-NoMoreCompanyLogo-1.0.2
Pooble-LCBetterSaves-1.7.3
ButteryStancakes-EnemySoundFixes-1.5.10
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.16.2
Silvercore-Permanent_Ladder-1.0.3
La_chips-AutoCompanyBuilding-1.2.1
readthisifbad-SnatchinBracken-1.5.1
TwinDimensionalProductions-CoilHeadStare-1.0.9
AudioKnight-StarlancerAIFix-3.8.4
Zaggy1024-OpenBodyCams-3.0.3
Evaisa-LethalThings-0.10.6
AinaVT-LethalConfig-1.4.3
Jordo-NeedyCats-1.2.2
Procyon-CatLaser-1.1.1
Piggy-Piggys_Variety_Mod-1.3.17
BMX-LobbyCompatibility-1.3.0
Evaisa-FixPluginTypesSerialization-1.1.1
MaxWasUnavailable-LethalModDataLib-1.2.2
Hardy-LCMaxSoundsFix-1.2.0
IAmBatby-LethalLevelLoader-1.3.13
IAmBatby-LethalToolbox-1.0.4
scoopy-Scoopys_Variety_Mod-1.2.0
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-LethalNetworkAPI-3.3.1
Piggy-LC_Office-1.2.7
sfDesat-Orion-2.1.4
x753-Mimics-2.6.4
Rune580-LethalCompany_InputUtils-0.7.7
Zingar-Atlas_Abyss-1.2.3
Magic_Wesley-Infernis-4.0.5
Alice-ScarletDevilMansion-2.1.0
stormytuna-RouteRandom-1.3.2
Dumbfabric-CustomPones-1.0.1
FlipMods-FasterItemDropship-1.3.1
EliteMasterEric-Coroner-2.2.0
EliteMasterEric-CoronerMimics-1.0.1
xilophor-StaticNetcodeLib-1.1.1
Sigurd-CSync-5.0.1
Scintesto-Monster_Plushies-1.2.9
AudioKnight-StarlancerWarehouse-1.6.7
AudioKnight-StarlancerMoons-2.4.0
Magic_Wesley-WesleysInteriors-1.6.2
zealsprince-Locker-1.6.1
Dev1A3-LethalFixes-1.2.4
Zaggy1024-PathfindingLagFix-1.4.0
ButteryStancakes-MeleeFixes-1.3.1
ButteryStancakes-WeedKillerFixes-1.1.0
ButteryStancakes-BarberFixes-1.2.2
ButteryStancakes-ButteryFixes-1.10.10
DiFFoZ-HarmonyXTranspilerFix-1.1.0
DiFFoZ-LethalPerformance-0.5.0
mattymatty-LobbyControl-2.4.10
SylviBlossom-TerminalConflictFix-1.2.2
ButteryStancakes-AccurateStaminaDisplay-2.2.0
fumiko-CullFactory-1.5.0
TheFluff-FairAI-1.4.1
Spyci-CozyImprovements-1.2.2
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
ficcialfaint-Spectator_Voice_Icon_Fix-1.0.0
NiceHairs-Symbiosis-1.0.8
mrov-MrovLib-0.2.13
mrov-TerminalFormatter-0.2.23
AdiBTW-Loadstone-0.1.18
XuXiaolan-ImmersiveScrap-1.4.1
ENZ-Lock_Doors_Mod-1.1.0
KayNetsua-E_Gypt_Moon-2.0.21
ascendtv-ScrapLossBalancer-1.0.0
Piggy-CruiserMap-1.0.5
HGG-JigglePhysicsPlugin-1.1.21
Mhz-MoreHead-1.2.6
boring-CustomTranslatorCharLimit-1.0.2
DiFFoZ-CompanyCruiserFix-1.0.5
DarthLilo-MagnetLock-1.2.0
Entity378-BuyableShotgunPlus-1.2.1
Rattenbonkers-TVLoader-1.1.2
ironbean-TVRandomizer-1.0.1
Nikki-FamilyGuyFunnyMomentsFixed-1.3.1
TeamClark-SCP_Foundation_Suit-1.1.0
NiceHairs-NuclearLibrary-1.0.7
Zehs-WesleysInteriorsAddon-1.1.0
Kittenji-Groan_Tube_Scrap-1.0.4
Nexor-FastKnife-0.0.4
necrowing-StopBeesOpeningDoors-1.1.0
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.6.5
mattymatty-DoNotEatItems-2.1.1
DiggC-CruiserImproved-1.4.1
mattymatty-AdditionalNetworking-2.1.2
FlipMods-ReservedItemSlotCore-2.0.39
FlipMods-ReservedFlashlightSlot-2.0.8
Alice-DungeonGenerationPlus-1.3.3
theMenagerie-LiminalPools-1.0.14
FlipMods-ReservedSprayPaintSlot-1.1.2
FlipMods-ReservedUtilitySlot-1.0.6
TestAccount666-TestAccountCore-1.12.0
TestAccount666-TestAccountFixes-1.3.5
Azim-LethalPresents-1.0.9
LegoMaster3650-FairGiants-1.1.2
LethalMatt-Bozoros-2.2.4
ButteryStancakes-RevisitStingers-1.2.1
mrgrm7-LethalCasino-1.1.2
DemonMae-unreal_interiors-1.9.2
mrov-ApparatusFix-0.0.1
DaJadeNinja-ChocoQuota-1.0.9
Hamunii-DetourContext_Dispose_Fix-1.0.3
Hamunii-AutoHookGenPatcher-1.0.4
NotAtomicBomb-TerminalApi-1.5.5
luakite-Synthesis_Moon-1.1.3
mrov-LethalRichPresence-0.5.9
ButteryStancakes-UpturnedVariety-1.0.2
ButteryStancakes-Chameleon-1.3.0
mborsh-Wider_Ship_Mod-1.3.11
DarthLilo-BabyManeater-1.1.2
DemonMae-ut99_interiors-1.6.2
ButteryStancakes-JetpackFixes-1.5.0
taffyko-NiceChat-1.2.7
darmuh-OpenLib-0.2.12
FlipMods-ReservedWalkieSlot-2.0.6
FlipMods-HotbarPlus-1.8.0
FlipMods-ReservedWeaponSlot-1.1.5
mattymatty-AsyncLoggers-2.1.3
mattymatty-BagConfig-0.0.5
JacobG5-JLL-1.8.0
LethalCompanyModding-VertexLibrary-1.1.0
Hamster-LethalPipeRemoval-1.7.6
SmoothReserve-SmoothReserves_Decor-1.1.3
FutureSavior-Hold_Scan_Button-1.1.2
AntlerShed-EnemySkinRegistry-1.4.6
slayer6409-Emergency_Dice_Updated-1.7.4
Zehs-MelaniesVoice-1.1.0
luakite-Vacuity_Moon-1.0.5
Generic_GMD-Generic_Interiors-1.1.1
LethalCompanyModding-RuntimeIcons-0.3.0
mattymatty-Matty_Fixes-1.1.31
SurfacedTeam-Surfaced-1.4.9
SolidStone-SolidLib-1.2.2
XuXiaolan-CodeRebirth-0.9.7
mrov-WeatherRegistry-0.3.11
DBJ-BetterScanVision-0.0.6
v0xx-LethalElements-1.1.8
etherealemil-UsualScrap-1.7.6
Zehs-Hitmarker-1.2.3
crump_laude-VisorColorsCosmetics-1.0.0
TestAccount666-AntiSlimeCamp-2.0.0
Dev1A3-BetterVehicleControls-1.1.3
ShaosilGaming-GeneralImprovements-1.4.4
mattymatty-LandFromOrbit-1.1.2
Hexnet111-SuitSaver-1.2.1
projectbots-MoonUnlockUnhide-1.2.1
Yorimor-CustomStoryLogs-1.4.5
JacobG5-LostEnemyFix-1.1.0
RosiePies-Rosies_Moons-2.2.8
coderCleric-Poltergeist-1.1.1
MelanieMelicious-MelanieMelicious_Utility_Furniture_Pack-0.3.2
NotezyTeam-EndOfDayCountdown_V2-1.0.1
AtomicStudio-Moved_Magnet_Switch-1.4.0
SylviBlossom-SaveItemRotations-1.0.0
Horsey4-RNGConfigurator-1.2.0
Rosentti-JesterTimeout-1.0.1
DemonMae-Gray_Apartments_Interior-1.1.1
Dev1A3-YesFox-1.0.9
Zehs-KidnapperFoxSettings-1.0.1
TopraksuK-FreeBirdTotemRemixJester-1.0.1
Zehs-Whiteboard-1.1.4
MelanieMelicious-MelanieMelicious_2_sToRy_ShIp__works_w_Wider_Ship_Mod-0.5.6
TestAccount666-ShipWindows-1.11.0
darmuh-suitsTerminal-1.5.12
LethalCompanyModding-Doorbelle-1.0.2
Hackattack242-ItemTertiaryUse_Conflict_Solver-1.0.0
Kittenji-NavMeshInCompany-1.0.3
Midge-PushCompany-1.2.0
qwbarch-Concentus-2.3.0
qwbarch-OpusDotNet-1.0.30
willis81808-LethalSettings-1.4.1
Bobbie-NAudio-2.2.2
qwbarch-MirageCore-1.0.3
qwbarch-Mirage-1.15.5
RosiePies-Rosies_Interiors-0.0.1
TestAccount666-TestAccountVariety-1.36.1
TestAccount666-DoorBreach-1.1.0
WhiteSpike-Interactive_Terminal_API-1.2.0
WarperSan-ShipInventory-1.1.8
Hamunii-TestingLib-1.2.1
Hamunii-DevTools-1.1.1
BatTeam-LethalFashion-1.0.7
Lega-SnowPlaygrounds-1.0.6
Dumbfabric-SpoolOfItems-1.0.0
mrov-BetaWeatherTweaksBeta-0.24.5
Piggy-LC_Shrimp-1.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
fixed
